import { useEffect, useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, MetricCard, ScreenTitle, Skeleton, uiStyles } from "../components/ui";
import { getReport, type ReportV2 } from "../lib";
import { colors, radii, spacing } from "../theme";

export function ReportsScreen() { const [report, setReport] = useState<ReportV2 | null>(null); const now = new Date(); const start = new Date(now); start.setDate(now.getDate() - 6); useEffect(() => { void getReport(start.toISOString().slice(0, 10), now.toISOString().slice(0, 10)).then(setReport); }, []); if (!report) return <ScrollView contentContainerStyle={uiStyles.content}><Skeleton rows={5} /></ScrollView>; const summary = report.summary; const maximum = Math.max(1, ...report.series.map((point) => point.booked_sales_minor)); return <ScrollView contentContainerStyle={uiStyles.content}><ScreenTitle title="Reports" subtitle="This week · booked and collected stay distinct" /><View style={styles.metrics}><MetricCard label="Booked sales" value={`${summary.currency_code} ${(summary.booked_sales_minor / 100).toLocaleString()}`} /><MetricCard label="Collected" value={`${summary.currency_code} ${(summary.collected_revenue_minor / 100).toLocaleString()}`} /><MetricCard label="Outstanding" value={`${summary.currency_code} ${(summary.outstanding_minor / 100).toLocaleString()}`} /><MetricCard label="Completed washes" value={String(summary.completed_washes)} /></View><Card><Text style={styles.cardTitle}>Revenue over time</Text><Text style={uiStyles.muted}>Booked sales by day</Text>{report.series.length ? report.series.map((point) => <View key={point.date} style={styles.graphRow}><Text style={styles.graphLabel}>{point.date.slice(5)}</Text><View style={styles.track}><View style={[styles.bar, { width: `${Math.max(3, point.booked_sales_minor / maximum * 100)}%` }]} /></View><Text style={styles.graphValue}>{(point.booked_sales_minor / 100).toFixed(0)}</Text></View>) : <EmptyState title="No report data for this period" />}</Card><Card><Text style={styles.cardTitle}>Job volume</Text>{report.series.map((point) => <View key={point.date} style={uiStyles.row}><Text style={uiStyles.muted}>{point.date}</Text><Text style={styles.graphValue}>{point.completed}/{point.jobs} completed</Text></View>)}</Card><Text style={styles.section}>EMPLOYEE PERFORMANCE</Text>{report.staff_performance.length ? report.staff_performance.map((item) => <Card key={item.id}><Text style={styles.cardTitle}>{item.name}</Text><View style={styles.performance}><Value label="Hours worked" value={item.hours_worked.toFixed(1)} /><Value label="Jobs completed" value={String(item.jobs_completed)} /><Value label="Avg wash" value={`${item.average_wash_minutes}m`} /><Value label="Jobs / hour" value={item.jobs_per_worked_hour.toFixed(2)} /></View><Text style={uiStyles.muted}>Job value handled · {summary.currency_code} {(item.job_value_handled_minor / 100).toLocaleString()}</Text></Card>) : <EmptyState title="No performance data" />}</ScrollView>; }
function Value({ label, value }: { label: string; value: string }) { return <View style={styles.value}><Text style={styles.valueNumber}>{value}</Text><Text style={styles.valueLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ metrics: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: spacing.sm }, cardTitle: { color: colors.text, fontSize: 18, fontWeight: "900" }, graphRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm }, graphLabel: { width: 40, color: colors.textSecondary, fontSize: 11 }, track: { flex: 1, height: 12, borderRadius: radii.pill, backgroundColor: colors.secondary, overflow: "hidden" }, bar: { height: "100%", backgroundColor: colors.primary, borderRadius: radii.pill }, graphValue: { width: 58, textAlign: "right", color: colors.text, fontWeight: "800" }, section: { color: colors.textSecondary, fontWeight: "900", fontSize: 11, letterSpacing: 1.2, marginTop: spacing.md }, performance: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, value: { width: "47%", backgroundColor: colors.surfaceElevated, padding: spacing.md, borderRadius: radii.md }, valueNumber: { color: colors.text, fontSize: 20, fontWeight: "900" }, valueLabel: { color: colors.textSecondary, fontSize: 11 } });
