import { useEffect, useState } from "react";
import { RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { capabilities } from "../capabilities";
import { AppButton, Card, EmptyState, MetricCard, ScreenTitle, Skeleton, StatusChip, uiStyles } from "../components/ui";
import { successHaptic } from "../haptics";
import { clockAttendance, getAttendance, getDashboard, getJobs, getShiftAssignments, type Attendance, type Dashboard, type Job, type ShiftAssignment, type StaffContext } from "../lib";
import { colors, spacing } from "../theme";

export function TodayScreen({ context }: { context: StaffContext }) {
  const management = capabilities(context.role).canViewAllJobs;
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [attendance, setAttendance] = useState<Attendance | null>(null);
  const [shift, setShift] = useState<ShiftAssignment | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { if (management) setDashboard(await getDashboard()); else { const [nextJobs, attendanceResult, shifts] = await Promise.all([getJobs("my"), getAttendance(), getShiftAssignments()]); setJobs(nextJobs); setAttendance(attendanceResult.items[0] ?? null); setShift(shifts[0] ?? null); } } catch { setError("We couldn't refresh operations. Pull down to try again."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [management]);
  async function clock() { try { setAttendance(await clockAttendance(attendance?.clock_out_at === null ? "clock-out" : "clock-in")); await successHaptic(); } catch { setError("The server did not confirm attendance. Please retry."); } }
  const next = jobs.find((job) => !["completed", "cancelled"].includes(job.status));
  return <ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()} />} contentContainerStyle={uiStyles.content}><ScreenTitle eyebrow={new Date().toLocaleDateString(undefined, { weekday: "long", day: "numeric", month: "long" }).toUpperCase()} title={`Good ${greeting()}, ${firstName(context.display_name)}`} subtitle={management ? "Live business operations" : "Everything you need for today's work"} />{error ? <Text style={uiStyles.error}>{error}</Text> : null}{loading && !dashboard && !jobs.length ? <Skeleton rows={4} /> : management ? <ManagerDashboard value={dashboard} /> : <><Card><View style={uiStyles.row}><View><Text style={styles.kicker}>ATTENDANCE</Text><Text style={styles.cardTitle}>{attendance?.clock_out_at === null ? "You're clocked in" : "Ready to start?"}</Text></View>{attendance ? <StatusChip value={attendance.status} /> : null}</View>{shift ? <Text style={uiStyles.muted}>Today's shift · {shortTime(shift.start_time)}–{shortTime(shift.end_time)}</Text> : <Text style={uiStyles.muted}>No shift assigned today</Text>}{attendance?.clock_out_at === null ? <Text style={styles.time}>Started {new Date(attendance.clock_in_at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })} · {formatMinutes(attendance.worked_minutes)}</Text> : null}<AppButton title={attendance?.clock_out_at === null ? "Clock out" : "Clock in"} tone={attendance?.clock_out_at === null ? "secondary" : "primary"} onPress={() => void clock()} /></Card>{next ? <Card><Text style={styles.kicker}>NEXT JOB</Text><Text style={styles.nextTime}>{new Date(next.scheduled_start).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</Text><Text style={styles.cardTitle}>{next.vehicles[0] ? `${next.vehicles[0].make} ${next.vehicles[0].model}` : next.customer_name}</Text><Text style={uiStyles.body}>{next.vehicles[0]?.service_name}</Text><Text style={uiStyles.muted}>{next.written_address}</Text><StatusChip value={next.status} /></Card> : <EmptyState title="No jobs today" body="Your next assigned or team job will appear here." />}</>}</ScrollView>;
}

function ManagerDashboard({ value }: { value: Dashboard | null }) { if (!value) return <EmptyState title="Dashboard unavailable" />; return <><View style={styles.metrics}>{value.metrics.slice(0, 4).map((metric) => <MetricCard key={metric.key} label={metric.label} value={metric.key === "booked" || metric.key === "collected" ? `${value.currency_code} ${(metric.value / 100).toLocaleString()}` : String(metric.value)} />)}</View><Text style={styles.section}>NEEDS ATTENTION</Text>{value.attention.length ? value.attention.map((item) => <Card key={item.kind}><View style={uiStyles.row}><Text style={styles.cardTitle}>{item.count}</Text><Text style={[uiStyles.body, { flex: 1 }]}>{item.label}</Text><Text style={uiStyles.link}>Review</Text></View></Card>) : <EmptyState title="Everything is under control" body="No operational items need attention." />}<Text style={styles.section}>ACTIVE NOW</Text>{value.active_jobs.length ? value.active_jobs.map((job) => <Card key={job.id}><View style={uiStyles.row}><View><Text style={styles.cardTitle}>{job.assigned_team_name ?? job.assigned_staff_name ?? "Unassigned"}</Text><Text style={uiStyles.muted}>{job.vehicles[0] ? `${job.vehicles[0].make} ${job.vehicles[0].model}` : job.booking_reference}</Text></View><StatusChip value={job.status} /></View></Card>) : <EmptyState title="No active jobs" />}</>; }
const greeting = () => { const hour = new Date().getHours(); return hour < 12 ? "morning" : hour < 18 ? "afternoon" : "evening"; };
const firstName = (name: string) => name.trim().split(/\s+/)[0] || "team";
const shortTime = (value: string) => value.slice(0, 5);
const formatMinutes = (value: number) => `${String(Math.floor(value / 60)).padStart(2, "0")}h ${String(value % 60).padStart(2, "0")}m`;
const styles = StyleSheet.create({ kicker: { color: colors.primary, fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, cardTitle: { color: colors.text, fontSize: 18, fontWeight: "900" }, time: { color: colors.text, fontSize: 16, fontWeight: "800" }, nextTime: { color: colors.text, fontSize: 30, fontWeight: "900" }, metrics: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: spacing.sm }, section: { color: colors.textSecondary, fontWeight: "900", fontSize: 12, letterSpacing: 1.2, marginTop: spacing.md } });
