"""initial_foundation

Revision ID: 86770d7ef2e1
Revises:
Create Date: 2026-08-23 02:06:12.429918
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "86770d7ef2e1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
        sa.UniqueConstraint("slug", name=op.f("uq_businesses_slug")),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("scope", sa.String(length=160), nullable=False),
        sa.Column("operation", sa.String(length=160), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "scope", "operation", "idempotency_key", name="uq_idempotency_scope_operation_key"
        ),
    )
    op.create_index("ix_idempotency_expiry", "idempotency_records", ["expires_at"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("actor_auth_user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_audit_events_business_id_businesses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_business_occurred", "audit_events", ["business_id", "occurred_at"], unique=False
    )
    op.create_table(
        "business_settings",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("opening_time", sa.Time(), nullable=False),
        sa.Column("closing_time", sa.Time(), nullable=False),
        sa.Column("slot_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("multi_vehicle_threshold", sa.Integer(), nullable=False),
        sa.Column("multi_vehicle_required_slots", sa.Integer(), nullable=False),
        sa.Column("cancellation_cutoff_hours", sa.Integer(), nullable=False),
        sa.Column("hold_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "closing_time > opening_time", name=op.f("ck_business_settings_valid_business_hours")
        ),
        sa.CheckConstraint(
            "multi_vehicle_required_slots > 0",
            name=op.f("ck_business_settings_positive_required_slots"),
        ),
        sa.CheckConstraint(
            "multi_vehicle_threshold > 0",
            name=op.f("ck_business_settings_positive_vehicle_threshold"),
        ),
        sa.CheckConstraint(
            "slot_duration_minutes > 0", name=op.f("ck_business_settings_positive_slot_duration")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_business_settings_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_settings")),
        sa.UniqueConstraint("business_id", name=op.f("uq_business_settings_business_id")),
    )
    op.create_table(
        "customer_profiles",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("auth_user_id", sa.Uuid(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_customer_profiles_business_id_businesses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_profiles")),
        sa.UniqueConstraint("auth_user_id", name=op.f("uq_customer_profiles_auth_user_id")),
    )
    op.create_index(
        "ix_customer_profiles_business_email",
        "customer_profiles",
        ["business_id", "email"],
        unique=False,
    )
    op.create_index(
        "ix_customer_profiles_business_phone",
        "customer_profiles",
        ["business_id", "phone"],
        unique=False,
    )
    op.create_table(
        "schedule_resources",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_schedule_resources_business_id_businesses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_resources")),
        sa.UniqueConstraint("business_id", "name", name=op.f("uq_schedule_resources_business_id")),
    )
    op.create_table(
        "services",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("vehicle_applicability", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_services_nonnegative_service_price")),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_services_business_id_businesses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_index(
        "ix_services_business_active_sort",
        "services",
        ["business_id", "is_active", "sort_order"],
        unique=False,
    )
    op.create_table(
        "staff_profiles",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("auth_user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('employee','manager','admin')", name=op.f("ck_staff_profiles_staff_role")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_staff_profiles_business_id_businesses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_profiles")),
        sa.UniqueConstraint("auth_user_id", name=op.f("uq_staff_profiles_auth_user_id")),
    )
    op.create_index(
        "ix_staff_profiles_business_active",
        "staff_profiles",
        ["business_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "customer_addresses",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("written_address", sa.Text(), nullable=False),
        sa.Column("location_url", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("location_instructions", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer_profiles.id"],
            name=op.f("fk_customer_addresses_customer_id_customer_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_addresses")),
    )
    op.create_table(
        "customer_payment_methods",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("provider_customer_id", sa.String(length=255), nullable=False),
        sa.Column("provider_payment_method_id", sa.String(length=255), nullable=False),
        sa.Column("card_brand", sa.String(length=40), nullable=True),
        sa.Column("last_four", sa.String(length=4), nullable=True),
        sa.Column("expiry_month", sa.Integer(), nullable=True),
        sa.Column("expiry_year", sa.Integer(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer_profiles.id"],
            name=op.f("fk_customer_payment_methods_customer_id_customer_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_payment_methods")),
        sa.UniqueConstraint(
            "provider_payment_method_id",
            name=op.f("uq_customer_payment_methods_provider_payment_method_id"),
        ),
    )
    op.create_table(
        "service_addons",
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_minor >= 0", name=op.f("ck_service_addons_nonnegative_addon_price")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_service_addons_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_addons")),
    )
    op.create_table(
        "slot_hold_groups",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("vehicle_count", sa.Integer(), nullable=False),
        sa.Column("required_slot_count", sa.Integer(), nullable=False),
        sa.Column("slot_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("slot_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','consumed','expired','released')",
            name=op.f("ck_slot_hold_groups_hold_status"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_slot_hold_groups_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["schedule_resources.id"],
            name=op.f("fk_slot_hold_groups_resource_id_schedule_resources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slot_hold_groups")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_slot_hold_groups_token_hash")),
    )
    op.create_index(
        "ix_hold_groups_expiry_status", "slot_hold_groups", ["status", "expires_at"], unique=False
    )
    op.create_table(
        "vehicles",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("vehicle_type", sa.String(length=80), nullable=False),
        sa.Column("colour", sa.String(length=80), nullable=True),
        sa.Column("plate_number", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer_profiles.id"],
            name=op.f("fk_vehicles_customer_id_customer_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
    )
    op.create_index(
        "ix_vehicles_customer_active", "vehicles", ["customer_id", "is_active"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=20), nullable=False),
        sa.Column("customer_profile_id", sa.Uuid(), nullable=True),
        sa.Column("hold_group_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("payment_choice", sa.String(length=30), nullable=False),
        sa.Column("payment_status", sa.String(length=30), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vehicle_count", sa.Integer(), nullable=False),
        sa.Column("total_amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("customer_first_name", sa.String(length=100), nullable=False),
        sa.Column("customer_surname", sa.String(length=100), nullable=False),
        sa.Column("customer_email", sa.String(length=320), nullable=False),
        sa.Column("customer_phone", sa.String(length=40), nullable=False),
        sa.Column("written_address", sa.Text(), nullable=False),
        sa.Column("location_url", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("location_instructions", sa.Text(), nullable=True),
        sa.Column("management_token_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "payment_choice IN ('pay_now','pay_after_service')",
            name=op.f("ck_bookings_booking_payment_choice"),
        ),
        sa.CheckConstraint(
            "payment_status IN ('unpaid','pending','paid','failed','refund_pending','refunded')",
            name=op.f("ck_bookings_booking_payment_status"),
        ),
        sa.CheckConstraint(
            "status IN ('pending_payment','confirmed','cancellation_requested',"
            "'cancelled','completed')",
            name=op.f("ck_bookings_booking_status"),
        ),
        sa.CheckConstraint(
            "total_amount_minor >= 0", name=op.f("ck_bookings_nonnegative_booking_total")
        ),
        sa.CheckConstraint(
            "vehicle_count > 0", name=op.f("ck_bookings_positive_booking_vehicle_count")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_bookings_business_id_businesses")
        ),
        sa.ForeignKeyConstraint(
            ["customer_profile_id"],
            ["customer_profiles.id"],
            name=op.f("fk_bookings_customer_profile_id_customer_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["hold_group_id"],
            ["slot_hold_groups.id"],
            name=op.f("fk_bookings_hold_group_id_slot_hold_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["schedule_resources.id"],
            name=op.f("fk_bookings_resource_id_schedule_resources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("hold_group_id", name=op.f("uq_bookings_hold_group_id")),
        sa.UniqueConstraint(
            "management_token_hash", name=op.f("uq_bookings_management_token_hash")
        ),
        sa.UniqueConstraint("reference", name=op.f("uq_bookings_reference")),
    )
    op.create_index(
        "ix_bookings_customer_history",
        "bookings",
        ["customer_profile_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_bookings_schedule_status",
        "bookings",
        ["business_id", "scheduled_start", "status"],
        unique=False,
    )
    op.create_table(
        "booking_vehicles",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("vehicle_type", sa.String(length=80), nullable=False),
        sa.Column("colour", sa.String(length=80), nullable=True),
        sa.Column("plate_number", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_vehicles_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"], ["vehicles.id"], name=op.f("fk_booking_vehicles_vehicle_id_vehicles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_vehicles")),
        sa.UniqueConstraint("booking_id", "position", name=op.f("uq_booking_vehicles_booking_id")),
    )
    op.create_table(
        "cancellation_requests",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("requester_type", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('requested','approved','rejected')",
            name=op.f("ck_cancellation_requests_cancellation_status"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_cancellation_requests_booking_id_bookings"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_staff_id"],
            ["staff_profiles.id"],
            name=op.f("fk_cancellation_requests_reviewed_by_staff_id_staff_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cancellation_requests")),
    )
    op.create_index(
        "ix_cancellations_status_created",
        "cancellation_requests",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('unassigned','assigned','in_progress','completed','cancelled')",
            name=op.f("ck_jobs_job_status"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_profiles.id"],
            name=op.f("fk_jobs_assigned_staff_id_staff_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["bookings.id"], name=op.f("fk_jobs_booking_id_bookings")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_jobs_business_id_businesses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("booking_id", name=op.f("uq_jobs_booking_id")),
    )
    op.create_index("ix_jobs_business_status", "jobs", ["business_id", "status"], unique=False)
    op.create_index(
        "ix_jobs_staff_status_schedule",
        "jobs",
        ["assigned_staff_id", "status", "scheduled_start"],
        unique=False,
    )
    op.create_table(
        "notification_outbox",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("notification_type", sa.String(length=80), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=160), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_notification_outbox_nonnegative_outbox_attempts")
        ),
        sa.CheckConstraint(
            "channel IN ('email','whatsapp','push')",
            name=op.f("ck_notification_outbox_notification_channel"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','processing','sent','retry','failed')",
            name=op.f("ck_notification_outbox_outbox_status"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["bookings.id"], name=op.f("fk_notification_outbox_booking_id_bookings")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_notification_outbox_business_id_businesses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_outbox")),
    )
    op.create_index(
        "ix_notification_outbox_claim",
        "notification_outbox",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=255), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_minor >= 0", name=op.f("ck_payments_nonnegative_payment_amount")
        ),
        sa.CheckConstraint(
            "status IN ('unpaid','pending','paid','failed','refund_pending','refunded')",
            name=op.f("ck_payments_payment_status"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["bookings.id"], name=op.f("fk_payments_booking_id_bookings")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index("ix_payments_booking", "payments", ["booking_id"], unique=False)
    op.create_index(
        "ix_payments_provider_id", "payments", ["provider", "provider_payment_id"], unique=False
    )
    op.create_table(
        "schedule_slots",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("slot_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("slot_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("hold_group_id", sa.Uuid(), nullable=True),
        sa.Column("hold_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column("blocked_reason", sa.String(length=240), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('free','held','reserved','blocked')",
            name=op.f("ck_schedule_slots_slot_status"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["bookings.id"], name=op.f("fk_schedule_slots_booking_id_bookings")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_schedule_slots_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["hold_group_id"],
            ["slot_hold_groups.id"],
            name=op.f("fk_schedule_slots_hold_group_id_slot_hold_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["schedule_resources.id"],
            name=op.f("fk_schedule_slots_resource_id_schedule_resources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_slots")),
        sa.UniqueConstraint("resource_id", "slot_start", name="uq_schedule_slot_resource_start"),
    )
    op.create_index(
        "ix_schedule_slots_active_hold",
        "schedule_slots",
        ["status", "hold_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_schedule_slots_resource_start_status",
        "schedule_slots",
        ["resource_id", "slot_start", "status"],
        unique=False,
    )
    op.create_table(
        "booking_services",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("booking_vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("service_name", sa.String(length=160), nullable=False),
        sa.Column("unit_price_minor", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("line_total_minor", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_booking_services_positive_booking_service_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_services_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["booking_vehicle_id"],
            ["booking_vehicles.id"],
            name=op.f("fk_booking_services_booking_vehicle_id_booking_vehicles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_booking_services_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_services")),
    )
    op.create_table(
        "job_events",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column("actor_staff_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column(
            "server_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("client_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_id", sa.String(length=160), nullable=True),
        sa.Column("client_event_id", sa.String(length=160), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_staff_id"],
            ["staff_profiles.id"],
            name=op.f("fk_job_events_actor_staff_id_staff_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["bookings.id"], name=op.f("fk_job_events_booking_id_bookings")
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
        sa.UniqueConstraint("job_id", "client_event_id", name=op.f("uq_job_events_job_id")),
    )
    op.create_index(
        "ix_job_events_job_timestamp", "job_events", ["job_id", "server_timestamp"], unique=False
    )
    op.create_table(
        "payment_transactions",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("provider_transaction_id", sa.String(length=255), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("provider_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_transactions_payment_id_payments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_transactions")),
    )
    op.create_index(
        "ix_payment_transactions_provider_id",
        "payment_transactions",
        ["provider_transaction_id"],
        unique=False,
    )
    # The backend is the only writer. Supabase Data API roles receive no policies.
    op.execute("ALTER TABLE businesses ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE business_settings ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE customer_profiles ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE customer_addresses ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE staff_profiles ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE services ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE service_addons ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE schedule_resources ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE slot_hold_groups ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE schedule_slots ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE bookings ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE booking_vehicles ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE booking_services ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE jobs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE job_events ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE payments ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE customer_payment_methods ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE cancellation_requests ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE notification_outbox ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE idempotency_records ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payment_transactions_provider_id", table_name="payment_transactions")
    op.drop_table("payment_transactions")
    op.drop_index("ix_job_events_job_timestamp", table_name="job_events")
    op.drop_table("job_events")
    op.drop_table("booking_services")
    op.drop_index("ix_schedule_slots_resource_start_status", table_name="schedule_slots")
    op.drop_index("ix_schedule_slots_active_hold", table_name="schedule_slots")
    op.drop_table("schedule_slots")
    op.drop_index("ix_payments_provider_id", table_name="payments")
    op.drop_index("ix_payments_booking", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_notification_outbox_claim", table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_index("ix_jobs_staff_status_schedule", table_name="jobs")
    op.drop_index("ix_jobs_business_status", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_cancellations_status_created", table_name="cancellation_requests")
    op.drop_table("cancellation_requests")
    op.drop_table("booking_vehicles")
    op.drop_index("ix_bookings_schedule_status", table_name="bookings")
    op.drop_index("ix_bookings_customer_history", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_vehicles_customer_active", table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index("ix_hold_groups_expiry_status", table_name="slot_hold_groups")
    op.drop_table("slot_hold_groups")
    op.drop_table("service_addons")
    op.drop_table("customer_payment_methods")
    op.drop_table("customer_addresses")
    op.drop_index("ix_staff_profiles_business_active", table_name="staff_profiles")
    op.drop_table("staff_profiles")
    op.drop_index("ix_services_business_active_sort", table_name="services")
    op.drop_table("services")
    op.drop_table("schedule_resources")
    op.drop_index("ix_customer_profiles_business_phone", table_name="customer_profiles")
    op.drop_index("ix_customer_profiles_business_email", table_name="customer_profiles")
    op.drop_table("customer_profiles")
    op.drop_table("business_settings")
    op.drop_index("ix_audit_business_occurred", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_idempotency_expiry", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_table("businesses")
    # ### end Alembic commands ###
